steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['ci', '--include', 'dev']
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
- name: 'node'
  entrypoint: 'npm'
  args: ['prune', '--omit', 'dev']